INSERT into CHARACTER values (1,'Bravoosi', 'knife', 'papa', 'male', 'mama', 'el mexicain', 'aucune');
INSERT into CHARACTER values (2,'Yoyo', 'knife', 'le patron', 'male', 'mama', 'Jean jean', 'aucune');
INSERT into CHARACTER_ALIASES values (1, 'alias1');
INSERT into CHARACTER_ALIASES values (1, 'alias2');
INSERT into CHARACTER_ALIASES values (2, 'alias3');
INSERT into CHARACTER_ALIASES values (2, 'alias4');
INSERT into CHARACTER_TITLES values (1, 'titre1');
INSERT into CHARACTER_TITLES values (1, 'titre2');
INSERT into CHARACTER_TITLES values (2, 'titre3');
INSERT into CHARACTER_TITLES values (2, 'titre4');