
package org.polytech.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BooksPort", targetNamespace = "http://spring.io/guides/gs-producing-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BooksPort {


    /**
     * 
     * @param getBooksRequest
     * @return
     *     returns org.polytech.client.GetBooksResponse
     */
    @WebMethod
    @WebResult(name = "getBooksResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getBooksResponse")
    public GetBooksResponse getBooks(
        @WebParam(name = "getBooksRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getBooksRequest")
        GetBooksRequest getBooksRequest);

    /**
     * 
     * @param getBookRequest
     * @return
     *     returns org.polytech.client.GetBookResponse
     */
    @WebMethod
    @WebResult(name = "getBookResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getBookResponse")
    public GetBookResponse getBook(
        @WebParam(name = "getBookRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getBookRequest")
        GetBookRequest getBookRequest);

}
