
package org.polytech.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BooksPortService", targetNamespace = "http://spring.io/guides/gs-producing-web-service", wsdlLocation = "file:/C:/Users/Epulapp/IdeaProjects/webservices/workshops/soap/src/books.wsdl")
public class BooksPortService
    extends Service
{

    private final static URL BOOKSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKSPORTSERVICE_EXCEPTION;
    private final static QName BOOKSPORTSERVICE_QNAME = new QName("http://spring.io/guides/gs-producing-web-service", "BooksPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Epulapp/IdeaProjects/webservices/workshops/soap/src/books.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKSPORTSERVICE_WSDL_LOCATION = url;
        BOOKSPORTSERVICE_EXCEPTION = e;
    }

    public BooksPortService() {
        super(__getWsdlLocation(), BOOKSPORTSERVICE_QNAME);
    }

    public BooksPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKSPORTSERVICE_QNAME, features);
    }

    public BooksPortService(URL wsdlLocation) {
        super(wsdlLocation, BOOKSPORTSERVICE_QNAME);
    }

    public BooksPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKSPORTSERVICE_QNAME, features);
    }

    public BooksPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BooksPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BooksPort
     */
    @WebEndpoint(name = "BooksPortSoap11")
    public BooksPort getBooksPortSoap11() {
        return super.getPort(new QName("http://spring.io/guides/gs-producing-web-service", "BooksPortSoap11"), BooksPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BooksPort
     */
    @WebEndpoint(name = "BooksPortSoap11")
    public BooksPort getBooksPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://spring.io/guides/gs-producing-web-service", "BooksPortSoap11"), BooksPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKSPORTSERVICE_EXCEPTION!= null) {
            throw BOOKSPORTSERVICE_EXCEPTION;
        }
        return BOOKSPORTSERVICE_WSDL_LOCATION;
    }

}
